version: "3.9"

services:

  myflaskapp:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: myflaskapp  

    restart: always

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    environment:
      - FLASK_ENV=production