name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy server
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            cd /var/www/myflaskapp
            git pull
            docker compose down
            docker compose up -d --build